app/profile/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, TextField
from wtforms.validators import Required, Length


class ProfileFrom(Form):
    first_name = StringField('First Name', validators=[Required(), Length(1, 64)])
    last_name = StringField('Last Name', validators=[Required(), Length(1, 64)])
    location = StringField('Current Location', validators=[Length(4, 64)])
    bio = TextField('Current Location')

app/profile/__init__.py
from flask import Blueprint

profile = Blueprint('profile', __name__)

from . import routes

app/profile/routes.py
from flask import render_template, flash, redirect, url_for
from flask.ext.login import login_required, current_user
from . import profile
from .forms import ProfileFrom
from ..models import User
from .. import db

@profile.route('/user/edit', methods=['GET', 'POST'])
def edit():
  form = ProfileFrom()
  if form.validate_on_submit():
    current_user.first_name = form.first_name.data
    current_user.last_name = form.last_name.data
    current_user.location = form.location.data
    current_user.bio = form.bio.data
    db.session.add(current_user._get_current_object())
    db.session.commit()
    flash('You profile has been updated')
    return redirect(url_for('profile.profile', username=current_user.username))
  form.first_name.data = current_user.first_name
  form.last_name.data = current_user.last_name
  form.location.data = current_user.location
  form.bio.data = current_user.bio
  return render_template('/profile/edit-profile.html', form = form, user=current_user)


@profile.route('/user/<username>')
def profile(username):
  user = User.query.filter_by(username=username).first_or_404()
  return render_template('/profile/profile.html', user = user)

app/templates/profile/edit-profile.html
{% extends 'base.html' %}

{% block content%}

 <!-- Page Title -->
    <div class="section section-breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>{{ current_user.username | capitalize }} Profile</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="section">
        <div class="container">
        <div class="row">
          <!-- Team Member -->
          <div class="col-md-4 col-sm-6">
            <div class="team-member">
              <!-- Team Member Photo -->
              {# <div class="team-member-image"><img src="{{ url_for('static', filename='img/team1.jpg') }}" alt="Name Surname"></div> #}
              <div class="team-member-image"><img src="{{ user.gravatar(200) }}" alt="Name Surname"></div>
              <div class="team-member-info">
                <ul>
                  <!-- Team Member Info & Social Links -->
                </ul>
              </div>
            </div>
          </div>
          <!-- End Team Member -->
          <div class="col-sm-6 product-details">
            <form action="" method="post"  class="form" role="form">
                {{ form.csrf_token }}
                <div class="form-group {% if form.first_name.errors %} has-error {% endif %} ">
                  <label for="{{ form.first_name.id }}"><i class="icon-user"></i> <b>First Name</b></label>
                  {{ form.first_name(class_="form-control") }}
                  {% if form.first_name.errors %}
                    <span class="help-block">{{ form.first_name.errors[0] }}</span>
                  {% endif %}
                </div>
                <div class="form-group {% if form.last_name.errors %} has-error {% endif %} ">
                  <label for="{{ form.last_name.id }}"><i class="icon-user"></i> <b>Last Name</b></label>
                  {{ form.last_name(class_="form-control") }}
                  {% if form.last_name.errors %}
                    <span class="help-block">{{ form.last_name.errors[0] }}</span>
                  {% endif %}
                </div>
                <div class="form-group {% if form.location.errors %} has-error {% endif %} ">
                  <label for="{{ form.location.id }}"><i class="icon-user"></i> <b>Location Name</b></label>
                  {{ form.location(class_="form-control") }}
                  {% if form.location.errors %}
                    <span class="help-block">{{ form.location.errors[0] }}</span>
                  {% endif %}
                </div>
                <div class="form-group {% if form.bio.errors %} has-error {% endif %} ">
                  <label for="{{ form.bio.id }}"><i class="icon-user"></i> <b>Bio</b></label>
                  {{ form.bio(class_="form-control") }}
                  {% if form.bio.errors %}
                    <span class="help-block">{{ form.bio.errors[0] }}</span>
                  {% endif %}
                </div>
                <button type="submit" class="btn pull-right">Submit</button>
                  <div class="clearfix"></div>
              </form>
          </div>
        </div>
      </div>
    </div>

{% endblock content%}

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block content%}

 <!-- Page Title -->
    <div class="section section-breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>{{ current_user.username | capitalize }} Profile</h1>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      {% for message in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{message}}
        </div>
      {% endfor %}
    </div>
    <div class="section">
        <div class="container">
        <div class="row">
          <!-- Team Member -->
          <div class="col-md-4 col-sm-6">
            <div class="team-member">
              <!-- Team Member Photo -->
              {# <div class="team-member-image"><img src="{{ url_for('static', filename='img/team1.jpg') }}" alt="Name Surname"></div> #}
              <div class="team-member-image"><img src="{{ user.gravatar(200) }}" alt="Name Surname"></div>
              <div class="team-member-info">
                <ul>
                  <!-- Team Member Info & Social Links -->
                </ul>
              </div>
            </div>
          </div>
          <!-- End Team Member -->

          <div class="col-sm-6 product-details">
              <h4>{{current_user.first_name}} {{current_user.last_name}}</h4>
            <h5>{{current_user.location}}</h5>
              <p>
                {{current_user.bio}}
              </p>
              <a href="{{ url_for('profile.edit')}}" class="btn btn"><i class="icon-shopping-cart icon-white"></i> Update Profile</a>
            </div>
        </div>
      </div>
    </div>

{% endblock content%}