app/metrics/__init__.py
from flask import Blueprint

metrics = Blueprint('metrics', __name__)

from . import routes

app/metrics/routes.py
from flask import render_template
from . import metrics
from ..models import TwitterTrend, TwitterUser, TrendTweet
from .. import db
from flask.ext.login import login_required
from sqlalchemy import func

from bokeh.plotting import figure
from bokeh.resources import CDN, INLINE
from bokeh.embed import file_html, components
from bokeh.charts import Bar

import pandas as pd
from bokeh.util.string import encode_utf8
# from bokeh.models import NumericalTickFormatter, ColumnDataSource



@metrics.route('/twitter')
@login_required
def twitter_home():
	top_users = db.session.query(TwitterUser).order_by(TwitterUser.followers_count.desc())[:10]
	top_trends = db.session.query(TwitterTrend).filter(TwitterTrend.trending == True).order_by(TwitterTrend.position)[:10]
	return render_template('metrics/index.html', top_trends=top_trends, top_users=top_users)


@metrics.route('/twitter/trends')
@login_required
def twitter_trends():
	top_trends = db.session.query(TwitterTrend).filter(TwitterTrend.trending == True).order_by(TwitterTrend.position)
	return render_template('metrics/twitter-trend.html', top_trends=top_trends)


@metrics.route('/twitter/trend/<int:id>/<order>')
@login_required
def twitter_trend(id, order='latest'):
	top_trend = db.session.query(TwitterTrend).filter(TwitterTrend.id == id).one()
	tweets = top_trend.tweets
	total_users = db.session.query(TrendTweet.tweeted_by).distinct().filter(TrendTweet.trend_id == id).count()
	# devices = tweets.query(func.count(TrendTweet.tweeted_using), TrendTweet.tweeted_using).group_by(TrendTweet.tweeted_using).order_by(func.count(TrendTweet.tweeted_using).desc()).all()
	devices = db.session.query(func.count(TrendTweet.tweeted_using), TrendTweet.tweeted_using).group_by(TrendTweet.tweeted_using).filter(TrendTweet.trend_id == top_trend.id).order_by(func.count(TrendTweet.tweeted_using).desc())[:5]

	df = pd.DataFrame(devices, columns=['Count', 'Source'])
	p = Bar(df, label='Source', values='Count', title="Top 5 Sources", color='#1ABB9C', responsive=True)
	p.logo = None
	p.toolbar_location = None

	css_resources = INLINE.render_css()
	js_resources = INLINE.render_js()
	script, div = components(p, INLINE)

	total_tweets = tweets.count()

	top_tweets = None
	if order == 'retweets':
		top_tweets = tweets.order_by(TrendTweet.retweet_count.desc())[:10]
	elif order == 'likes':
		top_tweets = tweets.order_by(TrendTweet.favourite_count.desc())[:10]
	elif order == 'latest':
		top_tweets = tweets.order_by(TrendTweet.tweeted_at.desc())[:10]
	html =  render_template('metrics/trend.html', top_trend=top_trend, total_tweets=total_tweets, devices=devices, total_users=total_users, top_tweets=top_tweets, order=order, script=script, div=div, js_resources=js_resources, css_resources=css_resources)

	return encode_utf8(html)


@metrics.route('/twitter/users')
@login_required
def twitter_users():
	twitter_users = db.session.query(TwitterUser).order_by(TwitterUser.followers_count.desc())
	return render_template('metrics/twitter-users.html', twitter_users=twitter_users)

app/templates/metrics/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Data Metrics! | Twitter Metrics</title>

    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='metrics/vendors/bootstrap/ver/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ url_for('static', filename='metrics/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{ url_for('static', filename='metrics/vendors/nprogress/nprogress.css') }}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{ url_for('static', filename='metrics/custom/css/custom.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='metrics/custom/css/snippets.css') }}" rel="stylesheet">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/dc/1.7.5/dc.css" rel="stylesheet">



  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Data Metrics!</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->

            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>Twitter</h3>
                <ul class="nav side-menu">
                	<li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ url_for('dashboard.scheduled_tweet') }}">Twitter Dashboard</a></li>
                    </ul>
                  </li>


                </ul>
              </div>
              <div class="menu_section">
                <h3>Facebook</h3>
                <ul class="nav side-menu">

                </ul>
              </div>

              <div class="menu_section">
                <h3>Real Estate</h3>
                <ul class="nav side-menu">

                </ul>
              </div>


            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->

            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            {% block content%}

            {% endblock content%}
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Data Metrics 2016 By <a href="https://colorlib.com">Samphil Technologies</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='metrics/vendors/jquery/ver/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ url_for('static', filename='metrics/vendors/bootstrap/ver/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ url_for('static', filename='metrics/vendors/fastclick/ver/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ url_for('static', filename='metrics/vendors/nprogress/nprogress.js') }}"></script>

    {{ moment.include_moment() }}
    <!-- Custom Theme Scripts -->

    {% block scripts %}

    {% endblock scripts %}

    <script src="{{ url_for('static', filename='metrics/custom/js/snippets.js')}}"></script>
    <script src="{{ url_for('static', filename='metrics/custom/js/custom.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.12/crossfilter.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/dc/1.7.5/dc.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js"></script>
    <script src="{{ url_for('static', filename='metrics/custom/js/queue.js')}}"></script>
    <script src="{{ url_for('static', filename='metrics/custom/js/graph.js')}}"></script>
  </body>
</html>

app/templates/metrics/index.html
{% extends "metrics/base.html" %}

{% block content %}

  <div class="page-title">
    <div class="title_left">
      <h3>Data Metrics Twitter Dashboard</h3>
    </div>
  </div>
  <div class="clearfix"></div>

<div class="row">

  <div class="col-md-6 col-sm-6 col-xs-12">


                <div class="x_panel">
                  <div class="x_title">
                    <h2>Top 5 Trends in Kenya <small>as of 43 minutes ago</small></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                  <div class="panel panel-success">
                      <div class="panel-body">
                          <div class="table-responsive">
                            <table class="table">
                              <thead>
                                <tr>
                                  <th>Trend</th>
                                  <th>Started</th>
                                  <th>Pos</th>
                                  <th>Prev Pos</th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for trend in top_trends %}
                                  <tr>
                                  <th scope="row"><a href="{{url_for('metrics.twitter_trend', id=trend.id, order='latest')}}">{{trend.name}}</a></th>
                                  <td>{{ moment(trend.started).fromNow(refresh=True) }}</td>
                                  <td>{{trend.position}}</td>
                                  <td>{{trend.prev_position}}</td>
                                </tr>
                                {% endfor %}


                              </tbody>
                            </table>
                          </div>
                      </div>
                      <div class="panel-footer">
                        <a href="{{ url_for('metrics.twitter_trends') }}" class="btn btn-primary">View All</a>
                      </div>
                  </div>
                  </div>
                </div>
  </div>



  <div class="col-md-3 col-sm-12 col-xs-12">
    <div>
      <div class="x_title">
        <h2>Top Profiles on Twitter</h2>
        <div class="clearfix"></div>
      </div>
      <ul class="list-unstyled top_profiles scroll-view">

      {% for twitter_user in top_users %}
        <li class="media event">
          <a href="javascript:;" class="pull-left">
                    <img src="{{twitter_user.profile_img_url}}" alt="" width="60" height="60">
                  </a>
          <div class="media-body">
            <a class="title" href="#">{{twitter_user.name}}</a>
            <p><strong>{{twitter_user.followers_count}} </strong> Followers </p>
            <p><strong>{{twitter_user.status_count}} </strong> Tweets </p>
          </div>
        </li>
      {% endfor %}


      </ul>
    </div>
  </div>

  <div class="col-md-3 col-sm-12 col-xs-12">
    <div>
      <div class="x_title">
        <h2>Top Brands on Twitter</h2>
        <div class="clearfix"></div>
      </div>
      <ul class="list-unstyled top_profiles scroll-view">
        <li class="media event">
          <a class="pull-left border-aero profile_thumb">
            <i class="fa fa-user aero"></i>
          </a>
          <div class="media-body">
            <a class="title" href="#">Ms. Mary Jane</a>
            <p><strong>$2300. </strong> Agent Avarage Sales </p>
            <p> <small>12 Sales Today</small>
            </p>
          </div>
        </li>
        <li class="media event">
          <a class="pull-left border-green profile_thumb">
            <i class="fa fa-user green"></i>
          </a>
          <div class="media-body">
            <a class="title" href="#">Ms. Mary Jane</a>
            <p><strong>$2300. </strong> Agent Avarage Sales </p>
            <p> <small>12 Sales Today</small>
            </p>
          </div>
        </li>
        <li class="media event">
          <a class="pull-left border-blue profile_thumb">
            <i class="fa fa-user blue"></i>
          </a>
          <div class="media-body">
            <a class="title" href="#">Ms. Mary Jane</a>
            <p><strong>$2300. </strong> Agent Avarage Sales </p>
            <p> <small>12 Sales Today</small>
            </p>
          </div>
        </li>
        <li class="media event">
          <a class="pull-left border-aero profile_thumb">
            <i class="fa fa-user aero"></i>
          </a>
          <div class="media-body">
            <a class="title" href="#">Ms. Mary Jane</a>
            <p><strong>$2300. </strong> Agent Avarage Sales </p>
            <p> <small>12 Sales Today</small>
            </p>
          </div>
        </li>
        <li class="media event">
          <a class="pull-left border-green profile_thumb">
            <i class="fa fa-user green"></i>
          </a>
          <div class="media-body">
            <a class="title" href="#">Ms. Mary Jane</a>
            <p><strong>$2300. </strong> Agent Avarage Sales </p>
            <p> <small>12 Sales Today</small>
            </p>
          </div>
        </li>
      </ul>
    </div>
  </div>

</div>


{% endblock content %}

app/templates/metrics/sample.html
{% extends "metrics/base.html" %}

{% block content %}

<div class="page-title">
  <div class="title_left">
    <h3>Plain Page</h3>
  </div>

  <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">Go!</button>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Header Page</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
          Page Contents
      </div>
    </div>
  </div>
</div>


{% endblock content %}

app/templates/metrics/trend.html
{% extends "metrics/base.html" %}
{% block content %}

{{js_resources|indent(4)|safe}}
{{css_resources|indent(4)|safe}}

<div class="page-title">
  <div class="title_left">
    <h3>Stats for {{top_trend.name}}</h3>
  </div>
</div>

<div class="clearfix"></div>
<div class="row tile_count">
      <div class="row top_tiles">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-wechat"></i></div>
                  <div class="count">{{total_tweets}}</div>
                  <h3>Total Tweets</h3>
                  <p>Counting only the original tweets</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-users"></i></div>
                  <div class="count">{{total_users}}</div>
                  <h3>Totals Users</h3>
                  <p>Users who tweeted the original tweet</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-sort-amount-desc"></i></div>
                  <div class="count">4,373</div>
                  <h3>Total Reach</h3>
                  <p>How many people have seen this trend</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-check-square-o"></i></div>
                  <div class="count">179</div>
                  <h3>Total Impressions</h3>
                  <p>People who have interacted with the trend</p>
                </div>
              </div>
            </div>
            </div>
            <div class="clearfix"></div>
<div class="row">
  <div class="col-md-6 col-sm-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
      {% if  order== 'retweets' %}
        <h2>Most Retweeted <small>Original tweets that were retweeted</small></h2>
      {% endif %}
      {% if  order== 'likes' %}
        <h2>Most Liked <small>Original tweets that were liked</small></h2>
      {% endif %}
      {% if  order== 'latest' %}
        <h2>Latest Tweets <small>Showing original tweets only</small></h2>
      {% endif %}
        <div class="panel_toolbox pull-right">
        {% if order== 'retweets' %}
          <a href="{{url_for('metrics.twitter_trend', id=top_trend.id, order='likes')}}" type="button" class="btn btn-primary btn-round btn-xs">By Most Liked</a>
          <a href="{{url_for('metrics.twitter_trend', id=top_trend.id, order='latest')}}" type="button" class="btn btn-success btn-round btn-xs">Show Latest</a>
        {% endif %}
        {% if order== 'likes' %}
          <a href="{{url_for('metrics.twitter_trend', id=top_trend.id, order='latest')}}" type="button" class="btn btn-success btn-round btn-xs">Show Latest</a>
          <a href="{{url_for('metrics.twitter_trend', id=top_trend.id, order='retweets')}}" type="button" class="btn btn-info btn-round btn-xs">By Most Retweets</a>
        {% endif %}
        {% if order== 'latest' %}
          <a href="{{url_for('metrics.twitter_trend', id=top_trend.id, order='likes')}}" type="button" class="btn btn-primary btn-round btn-xs">By Most Liked</a>
        <a href="{{url_for('metrics.twitter_trend', id=top_trend.id, order='retweets')}}" type="button" class="btn btn-info btn-round btn-xs">By Most Retweets</a>
        {% endif %}
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
      <div class="col-md-12 col-sm-12 col-xs-12">
        {% for trend in top_tweets %}
            <div class="panel panel-default panel-google-plus">
                <div class="dropdown">
                    <span class="dropdown-toggle" type="button" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </span>
                    <ul class="dropdown-menu" role="menu">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">View on Twitter</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Retweet</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Follow</a></li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Report Issue</a></li>
                    </ul>
                </div>
                <div class="panel-heading">
                    <img class="img-circle pull-left" src="{{trend.profile_img_url}}" width="45" height="45" />
                    <h3>{{trend.user_name}}</h3>
                    <h5><span>@{{trend.tweeted_by}}</span> - <span>{{ moment(trend.tweeted_at).fromNow(refresh=True) }}</span> </h5>
                </div>
                <div class="panel-body">
                    {{trend.text}}
                </div>
                <div class="panel-footer">
                  <i class="fa fa-retweet"></i> {{trend.retweet_count}} &nbsp;|&nbsp; <i class="fa fa-heart"></i> {{trend.favourite_count}}
                </div>
            </div>
          {% endfor %}
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12">
      </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-6 col-xs-12">
  <div class="x_panel">
                <div class="x_title">
                  <h2>Sources of tweets Analysis</h2>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
<div class="col-md-12 col-sm-12 col-xs-12">
                {{script|indent(4)|safe}}
                {{div|indent(4)|safe}}
</div>

                </div>
              </div>
  </div>
</div>


{% endblock content %}

app/templates/metrics/twitter-trend.html
{% extends "metrics/base.html" %}
{% block content %}

<div class="page-title">
  <div class="title_left">
    <h3>Plain Page</h3>
  </div>

  <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">Go!</button>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Header Page</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <p class="text-muted font-13 m-b-30">
          Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
        </p>
        <div class="table-responsive">

        <table class="table table-striped ">
            <thead>
              <tr>
                <th>#</th>
                <th>Trend</th>
                <th>Started</th>
                <th>Prev Pos</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
            {% for trend in  top_trends %}
                <tr>
                  <td>{{trend.position}}</td>
                  <td>{{trend.name}}</td>
                  <td>{{ moment(trend.started).fromNow(refresh=True) }}</td>
                  <td>{{trend.prev_position}}</td>
                  <td>
                    {% if trend.prev_position %}
                          {% if  trend.position > trend.prev_position %}
                            <i class="fa fa-level-down"></i>
                          {% elif trend.position == trend.prev_position %}
                            <i class="fa fa-arrows-h"></i>
                          {% else %}
                            <i class="fa fa-level-up"></i>
                          {% endif %}
                    {% else %}
                        <i class="fa fa-level-up"></i>
                    {% endif %}

                  </td>
                  <td>
                    <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                    <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                    <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                  </td>
              </tr>
            {% endfor %}
            </tbody>
        </table>

        </div>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

app/templates/metrics/twitter_dashboard_sample.html
{% extends "metrics/base.html" %}

{% block content %}
	<!-- END PAGE TITLE-->
	<div class="page-title">
	  <div class="title_left">
	    <h3>Twitter Dashboard</h3>
	  </div>
	</div>
	<div class="clearfix"></div>
	<!-- END PAGE TITLE-->



	<div class="row">

<!-- START OF TREND-->
		<div class="col-md-5 col-sm-5 col-xs-12">
		  <div class="x_panel">
		    <div class="x_title">
		      <h2>Currently Trending in Kenya <small>Refreshed 20 Mins ago</small></h2>
		      <div class="clearfix"></div>
		    </div>
		    <div class="x_content">

			<div class="table-responsive">
			  <table class="table">
			    <thead>
			      <tr>
			        <th>Pos</th>
			        <th>Trend</th>
			        <th>Started</th>
			        <th>Prev Pos</th>
			      </tr>
			    </thead>
			    <tbody>
			      {% for trend in top_trends %}
			        <tr>
			        <td>{{trend.position}}</td>
			        <th scope="row"><a href="{{url_for('metrics.twitter_trend', id=trend.id)}}">{{trend.name}}</a></th>
			        <td>{{ moment(trend.started).fromNow(refresh=True) }}</td>
			        <td>{{trend.prev_position}}</td>
			      </tr>
			      {% endfor %}
			    </tbody>
			  </table>
			</div>

		    </div>
		  </div>
		  <div class="x_panel">
		    <div class="x_title">
		      <h2>Currently Trending in Kenya <small>Refreshed 20 Mins ago</small></h2>
		      <div class="clearfix"></div>
		    </div>
		    <div class="x_content">

			<div class="table-responsive">
			  <table class="table">
			    <thead>
			      <tr>
			        <th>Pos</th>
			        <th>Trend</th>
			        <th>Started</th>
			        <th>Prev Pos</th>
			      </tr>
			    </thead>
			    <tbody>
			      {% for trend in top_trends %}
			        <tr>
			        <td>{{trend.position}}</td>
			        <th scope="row"><a href="{{url_for('metrics.twitter_trend', id=trend.id)}}">{{trend.name}}</a></th>
			        <td>{{ moment(trend.started).fromNow(refresh=True) }}</td>
			        <td>{{trend.prev_position}}</td>
			      </tr>
			      {% endfor %}
			    </tbody>
			  </table>
			</div>

		    </div>
		  </div>
		</div>
	<!-- END OF TRENDS -->

	<div class="col-md-7 col-sm-7 col-xs-12">
	<div class="x_panel">
		    <div class="x_title">
		      <h2>Influencial Twitter Accounts In Kenya <small>Ranked by # of followers</small></h2>
		      <div class="clearfix"></div>
		    </div>
		    <div class="x_content">
	{% for twitter_user in top_users %}
		<div class="col-md-6 col-sm-6 col-xs-12 widget widget_tally_box">
		  <div class="x_panel fixed_height_390">
		    <div class="x_content">

		      <div class="flex">
		      <div class="row">
		      	<div class="tile-stats"><span class="count">{{loop.index}}</span></div>
		      </div>
		        <ul class="list-inline widget_profile_box">
		          <li>
		            <a>
		              <i class="fa fa-facebook"></i>
		            </a>
		          </li>
		          <li>
		            <img src="{{twitter_user.profile_img_url}}" alt="" class="img-circle profile_img">
		          </li>
		          <li>
		            <a>
		              <i class="fa fa-twitter"></i>
		            </a>
		          </li>
		        </ul>
		      </div>

		      <h3 class="name">{{twitter_user.name}}</h3>
			<p>
		        {{twitter_user.description}}
		      </p>
		      <div class="flex">
		        <ul class="list-inline count2">
		          <li>
		            <h4>{{twitter_user.followers_count}}</h4>
		            <span><strong>Followers</strong></span>
		          </li>
		          <li>
		            <h4>{{twitter_user.followers_count}}</h4>
		            <span><strong>Following</strong></span>
		          </li>
		          <li>
		            <h4>{{twitter_user.status_count}}</h4>
		            <span><strong>Tweets</strong></span>
		          </li>
		        </ul>
		      </div>
		    </div>
		  </div>
		</div>
	{% endfor %}
	</div>
	</div>






	</div>





{% endblock content %}