app/blog/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextField, SubmitField
from wtforms.validators import Required, Length, Email, Optional, URL,Regexp
from wtforms.widgets import TextArea
from werkzeug.utils import secure_filename
from flask_wtf.file import FileField, FileAllowed, FileRequired
# from flask_pagedown.fields import PageDownField
from flask.ext.pagedown.fields import PageDownField


class PostForm(Form):
	title = StringField('Title', validators=[Required(), Length(1, 64)])
	body = PageDownField('Body', validators=[Required()])
	posted = BooleanField('Post')
	featured_image = FileField('featured_image', validators=[FileAllowed(['jpg', 'png'], 'Upload Images only!')])
	video = StringField('Video Link', validators=[Optional(), URL()])


class CommentForm(Form):
	name = StringField('Your Name', validators=[Required(), Length(7, 64, "Atleast Two Names required")],)
	email = StringField('Your Email', validators=[Required(), Length(5, 64), Email()])
	body = PageDownField('Your Message', validators=[Required()])
	notify = BooleanField('Notify me when new comments are posted for this post', default=True)

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField
from wtforms.validators import Required, Length, Email
from wtforms.widgets import TextArea


class ContactForm(Form):
	name = StringField('Your name', validators=[Required(), Length(7, 64, "Atleast Two Names required")],)
	email = StringField('Email', validators=[Required(), Length(5, 64), Email()])
	body = StringField('Message', widget=TextArea(), validators=[Required()])

app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import routes

app/blog/routes.py
from flask import render_template, redirect, url_for, current_app, flash
from flask.ext.login import current_user
from werkzeug.utils import secure_filename
from . import blog
from .forms import PostForm, CommentForm
from ..models import BlogPost, BlogComments
from .. import db
import os
import uuid
import re
from datetime import datetime


@blog.route('/new', methods=['POST', 'GET'])
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		filename = secure_filename(form.featured_image.data.filename)
		extension = filename.rsplit('.', 1)[1]
		featured_image = str(uuid.uuid4()) + '.' + extension
		form.featured_image.data.save(os.path.join(current_app.config['UPLOAD_FOLDER'], featured_image))
		title = form.title.data
		body = form.body.data
		posted = form.posted.data
		video = form.video.data
		slug = re.sub('[^\w]+', '-', title.lower()).strip('-')
		publish_date = None
		if posted is True:
			publish_date = datetime.utcnow()
		post = BlogPost(title=title, body=body, publish_date=publish_date, posted=posted, slug=slug, featured_image=featured_image, video=video, author=current_user._get_current_object()	)
		db.session.add(post)
		db.session.commit()
		return redirect(url_for('main.blog'))
	return render_template('blog/new_post.html', form=form)


@blog.route('/<slug>', methods=['GET', 'POST'])
def post(slug):
	post = BlogPost.query.filter_by(slug=slug).first_or_404()
	comment = None
	form = CommentForm()
	if form.validate_on_submit():
		comment = BlogComments(author_name = form.name.data, author_email = form.email.data, body = form.body.data, notify = form.notify.data, approved=False, post=post)
	if comment:
		db.session.add(comment)
		db.session.commit()
		flash("Thanks you for your comment. It will be published shortly after it has been moderated")
		return redirect(url_for('.post', slug=post.slug) + '#top')
	comments = post.comments.order_by(BlogComments.publish_date.asc()).all()
	return render_template('/blog/post.html', post=post, form=form, comments=comments)


@blog.route('/edit/<slug>', methods=['POST', 'GET'])
def edit_post(slug):
	post = BlogPost.query.filter_by(slug=slug).first_or_404()
	form = PostForm(obj=post)
	if form.validate_on_submit():
		if form.featured_image.data:
			filename = secure_filename(form.featured_image.data.filename)
			extension = filename.rsplit('.', 1)[1]
			featured_image = str(uuid.uuid4()) + '.' + extension
			form.featured_image.data.save(os.path.join(current_app.config['UPLOAD_FOLDER'], featured_image))
		post.title = form.title.data
		post.body = form.body.data
		post.posted = form.posted.data
		post.video = form.video.data
		post.slug = re.sub('[^\w]+', '-', form.title.data.lower()).strip('-')
		db.session.add(post)
		db.session.commit()
		return redirect(url_for('main.blog'))
	return render_template('blog/new_post.html', form=form, post=post)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for
from ..email import send_email
from . import main
from ..models import BlogPost
from ..models import TwitterTrend, TwitterUser, TrendTweet, TrendUserActivity, TrendAppUsage, TrendTopTweets, ScheduledTweets, ScheduledTopTrending
from sqlalchemy import func
from .. import db
from .. import cache
# from flask.ext.cache.Cache import cache
from .forms import ContactForm

from bokeh.charts import Bar, Donut
from bokeh.resources import INLINE
from bokeh.embed import components
import pandas as pd
from bokeh.util.string import encode_utf8
from ..utils import percentage
from flask.ext.login import login_required
from datetime import datetime


@main.route('/')
def index():
	return render_template('main/index.html')


@main.route('/about')
def about():
	return render_template('main/about.html')


@main.route('/scheduled-tweet/<int:id>',)
@login_required
def sheduled_tweet(id):
	tweet = db.session.query(ScheduledTweets).filter(ScheduledTweets.id == id).one()
	tweet.posted = True
	db.session.add(tweet)
	db.session.commit()
	return redirect(url_for('main.scheduled_tweet'))


@main.route('/scheduled-toptrending/<int:id>',)
@login_required
def sheduled_toptrending(id):
	tweet = db.session.query(ScheduledTopTrending).filter(ScheduledTopTrending.id == id).one()
	tweet.posted = True
	db.session.add(tweet)
	db.session.commit()
	return redirect(url_for('main.scheduled_tweet'))


@main.route('/scheduled-tweets', methods=['GET', 'POST'])
@login_required
def scheduled_tweet():
	tweets = db.session.query(ScheduledTweets).filter(ScheduledTweets.posted == False).order_by(ScheduledTweets.generated_on.desc()).all()
	top_trends = db.session.query(ScheduledTopTrending).filter(ScheduledTopTrending.posted == False).order_by(ScheduledTopTrending.generated_on.desc()).all()
	return render_template('main/scheduled_tweets.html', tweets=tweets, top_trends=top_trends)


@main.route('/contact', methods=['GET', 'POST'])
def contact():
	form = ContactForm()
	if form.validate_on_submit():
		name = form.name.data
		email = form.email.data
		body = form.body.data
		subject = "CONTACT US FROM {}, EMAIL: {}".format(name, email)
		to = 'info@datametrics.co.ke'
		send_email(to, subject, "email/contact_us", name=name, message=body)
		flash('Thank you {} for your message.\bWe shall get back to you shortly'.format(name), 'info')
		return redirect(url_for('main.contact'))
	return render_template('main/contact.html', form=form)

@main.route('/faq')
def faq():
	return render_template('main/fag.html')

@main.route('/blog')
def blog():
	posts = BlogPost.query.order_by(BlogPost.draft_date.desc())
	return render_template('main/blog.html', posts=posts)


@main.route('/twitter')
def twitter():
	top_users = db.session.query(TwitterUser).order_by(TwitterUser.followers_count.desc())[:10]
	top_trends = db.session.query(TwitterTrend).filter(TwitterTrend.trending == True).order_by(TwitterTrend.position)[:10]
	today_midnight = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)
	recently_trending = db.session.query(TwitterTrend).filter(TwitterTrend.total_retweets != None, TwitterTrend.ended> today_midnight).order_by(TwitterTrend.ended.desc())[:15]
	return render_template('main/twitter-home.html', top_trends=top_trends, top_users=top_users, recently_trending=recently_trending)


@main.route('/twitter/trend/<int:id>/')
@cache.memoize(timeout=10000)
def trend_details(id):
	trend = db.session.query(TwitterTrend).filter(TwitterTrend.id == id).one()
	total_tweets = trend.total_tweets + trend.total_retweets
	tweets_percentage = percentage(trend.total_tweets, total_tweets)
	retweets_percentage = percentage(trend.total_retweets, total_tweets)
	apps_usage = trend.apps.order_by(TrendAppUsage.count.desc())[:5]
	top_tweets = trend.top_tweets.order_by(TrendTopTweets.retweet_count.desc())[:10]
	users_activity = trend.users_activity
	users_tweets = users_activity.filter(TrendUserActivity.tweets != None).order_by(TrendUserActivity.tweets.desc())[:10]
	users_retweets = users_activity.filter(TrendUserActivity.retweets != None).order_by(TrendUserActivity.retweets.desc())[:10]

	apps_usage_list = []
	for app in apps_usage:
		app_usage = (app.app_name, app.count)
		apps_usage_list.append(app_usage)
	df = pd.DataFrame(apps_usage_list, columns=['app_name', 'count'])
	p = Bar(df, label='app_name', values='count', color='#1ABB9C', responsive=True)
	p.logo = None
	p.toolbar_location = None
	apps_usage_script, apps_usage_div = components(p, INLINE)

	data = pd.Series([trend.total_tweets, trend.total_retweets], index=['tweets', 'retweets'])
	pie_chart = Donut(data, responsive=True)
	pie_chart.logo = None
	pie_chart.toolbar_location = None

	pie_script, pie_div = components(pie_chart, INLINE)



	css_resources = INLINE.render_css()
	js_resources = INLINE.render_js()

	html =  render_template('main/trend_detail.html', trend=trend, js_resources=js_resources, css_resources=css_resources,  tweets_percentage=tweets_percentage, retweets_percentage=retweets_percentage, apps_usage_script=apps_usage_script, apps_usage_div=apps_usage_div, pie_script=pie_script, pie_div=pie_div, top_tweets=top_tweets, users_retweets=users_retweets, users_tweets=users_tweets)

	return encode_utf8(html)


@main.route('/twitter/trend/<int:id>/<order>')
# @cache.memoize(timeout=300)
def trend(id, order='latest'):
	trend = db.session.query(TwitterTrend).filter(TwitterTrend.id == id).one()
	# trend_users_tweets = db.session.query(TrendUserActivity).filter(TrendUserActivity.trend_id == id, TrendUserActivity.tweets != None).order_by(TrendUserActivity.tweets.desc())[:10]
	# trend_users_retweets = db.session.query(TrendUserActivity).filter(TrendUserActivity.trend_id == id, TrendUserActivity.retweets != None).order_by(TrendUserActivity.retweets.desc())[:10]
	tweets = trend.tweets
	users_activity = trend.users_activity
	trend_users_tweets = users_activity.filter(TrendUserActivity.tweets != None).order_by(TrendUserActivity.tweets.desc())[:10]
	trend_users_retweets = users_activity.filter(TrendUserActivity.retweets != None).order_by(TrendUserActivity.retweets.desc())[:10]
	total_users = db.session.query(TrendTweet.tweeted_by).distinct().filter(TrendTweet.trend_id == id).count()
	devices = db.session.query(func.count(TrendTweet.tweeted_using), TrendTweet.tweeted_using).group_by(TrendTweet.tweeted_using).filter(TrendTweet.trend_id == trend.id).order_by(func.count(TrendTweet.tweeted_using).desc())[:5]
	print devices
	# influencers = db.session.query(TrendTweet.tweeted_by, TrendTweet.followers_count, TrendTweet.friends_count, TrendTweet.user_name, TrendTweet.statuses_count, TrendTweet.profile_img_url).distinct(TrendTweet.tweeted_by).filter(TrendTweet.trend_id == id).all()

	script = ""
	div = ""
	css_resources = INLINE.render_css()
	js_resources = INLINE.render_js()
	if len(devices) > 0:
		df = pd.DataFrame(devices, columns=['Count', 'Source'])
		p = Bar(df, label='Source', values='Count', color='#1ABB9C', responsive=True)
		p.logo = None
		p.toolbar_location = None

		script, div = components(p, INLINE)

	total_tweets = tweets.filter(TrendTweet.retweet == None).count()
	retweets = tweets.filter(TrendTweet.retweet == True).count()

	tweets_percentage = percentage(total_tweets, tweets.count())
	retweets_percentage = percentage(retweets, tweets.count())



	data = pd.Series([total_tweets, retweets], index=['tweets', 'retweets'])
	pie_chart = Donut(data, responsive=True)
	pie_chart.logo = None
	pie_chart.toolbar_location = None

	pie_script, pie_div = components(pie_chart, INLINE)

	top_tweets = None
	if order == 'retweets':
		top_tweets = tweets.filter(TrendTweet.retweet == None).order_by(TrendTweet.retweet_count.desc())[:5]
	elif order == 'likes':
		top_tweets = tweets.filter(TrendTweet.retweet == None).order_by(TrendTweet.favourite_count.desc())[:5]
	elif order == 'latest':
		top_tweets = tweets.filter(TrendTweet.retweet == None).order_by(TrendTweet.tweeted_at.desc())[:5]
	elif order == 'oldest':
		top_tweets = tweets.filter(TrendTweet.retweet == None).order_by(TrendTweet.tweeted_at)[:5]
	html =  render_template('main/trend.html', trend=trend, total_tweets=total_tweets, devices=devices, total_users=total_users, top_tweets=top_tweets, order=order, script=script, div=div, js_resources=js_resources, css_resources=css_resources, retweets=retweets, pie_script=pie_script, pie_div=pie_div, tweets_percentage=tweets_percentage, retweets_percentage=retweets_percentage, trend_users_tweets=trend_users_tweets, trend_users_retweets=trend_users_retweets)

	return encode_utf8(html)


@main.app_errorhandler(404)
def page_not_found(e):
	return render_template('404.html'), 404


@main.app_errorhandler(500)
def internal_server_error(e):
	return render_template('500.html'), 500

app/templates/main/blog.html
{% extends 'base.html' %}

{% block content%}

      <!-- Page Title -->
    <div class="section section-breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1 class="pull-left">The Latest from our blog</h1>
            {% if  current_user.is_authenticated %}
              <a href="{{url_for('blog.new_post')}}" class="btn btn-small pull-right">New Post</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

      <!-- Posts List -->
        <div class="section blog-posts-wrapper">
        <div class="container">
        <div class="row">
          <!-- Post -->
          {% for post in posts %}
              <div class="col-md-4 col-sm-6">
                <div class="blog-post">
                  <!-- Post Info -->
                  <div class="post-info">
                    <div class="post-date">
                      <div class="date">3 Days Ago</div>
                    </div>
                    <div class="post-comments-count">
                      <a href="page-blog-post-right-sidebar.html" title="Show Comments"><i class="glyphicon glyphicon-comment icon-white"></i>11</a>
                    </div>
                  </div>
                  <!-- End Post Info -->
                  <!-- Post Image -->
                  <a href="page-blog-post-right-sidebar.html"><img src="{{url_for('static', filename='uploads')}}/{{post.featured_image}}" class="post-image" alt="Post Title"></a>
                  <!-- End Post Image -->
                  <!-- Post Title & Summary -->
                  <div class="post-title">
                    <h3><a href="{{ url_for('blog.post', slug=post.slug) }}">{{post.title}}</a></h3>
                  </div>
                  <div class="post-summary">
                    <p>{{ post.body_html | safe | truncate(150) }}    </p>
                  </div>
                  <!-- End Post Title & Summary -->
                  <div class="post-more">
                    <a href="{{ url_for('blog.post', slug=post.slug) }}" class="btn btn-small">Read more</a>
                    {% if  current_user.is_authenticated %}
                      <a href="{{ url_for('blog.edit_post', slug=post.slug) }}" class="btn btn-small pull-left">Edit</a>
                    {% endif %}
                  </div>
                </div>
              </div>
          {% endfor %}



        </div>
      </div>
      </div>
      <!-- End Posts List -->

{% endblock content%}

app/templates/main/fag.html
{% extends 'base.html' %}

{% block content%}

        <!-- Page Title -->
		<div class="section section-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Frequently Asked Questions</h1>
					</div>
				</div>
			</div>
		</div>

        <div class="section">
			<div class="container">
				<div class="row">
					<div class="col-md-12 faq-wrapper">
						<div class="panel-group" id="accordion2">
							<h3>General Questions</h3>
							<div class="panel panel-default">
								<div class="panel-heading">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse11">
										How are influencers of a twitter trend/hashtag determined?
									</a>
								</div>
								<div id="collapse11" class="accordion-body collapse">
									<div class="accordion-inner">
										<div class="answer">Answer:</div>
										<p>Influencers of a twitter trend/hashtag is arrived at by factoring the number friends of every account (twitter user) that tweets about the trend/hashtag. The account that has the highest number of friends influencers the trend/hashtag most as it means many people (friends following this account) will and probaly get engaged with the trend</p>
									</div>
								</div>
							</div>
							</div>

							</div>
						</div>
					</div>
				</div>
			</div>
	    </div>
{% endblock content%}

app/templates/main/scheduled_tweets.html
{% extends 'base.html' %}

{% block content%}

        <!-- Page Title -->
    <div class="section section-breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>Scheduled Tweets</h1>
          </div>
        </div>
      </div>
    </div>

  <div class="section">
    <div class="container">
      <div class="row">
        <div class="table-responsive">
        <h2>Scheduled Tweets to be tweeted</h2>
  <p>Tweets to be tweeted. Remember after tweeting change the status of the tweet by clicking update</p>
  <table class="table">
    <thead>
      <tr>
        <th><strong>Trend</strong></th>
        <th><strong>Tweet</strong></th>
        <th><strong>Generated</strong></th>
        <th><strong>Update</strong></th>
      </tr>
    </thead>
    <tbody>
    {% for tweet in tweets %}
      <tr>
        <td>{{tweet.trend.name}}</td>
        <td>{{tweet.tweet_text}}</td>
        <td>{{tweet.generated_on}}</td>
        {# <td><a href="#">Update</a></td> #}
        <td class="actions">
                  <a href="{{url_for('main.sheduled_tweet', id=tweet.id)}}" class="btn btn-sm btn-blue"><i class="glyphicon glyphicon-pencil"></i></a>
                </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
        </div>
      </div>


    <div class="row">
      <div class="table-responsive">
      <h2>Top Trending Hashtags to be tweeted</h2>
    <p>Trends to be tweeted. Remember after tweeting change the status of the tweet by clicking update</p>
      <table class="table">
      <thead>
      <tr>
        <th><strong>Tweet</strong></th>
        <th><strong>Generated</strong></th>
        <th><strong>Update</strong></th>
      </tr>
      </thead>
      <tbody>
      {% for tweet in top_trends %}
      <tr>
        <td>{{tweet.tweet_text}}</td>
        <td>{{tweet.generated_on}}</td>
        {# <td><a href="#">Update</a></td> #}
        <td class="actions">
                  <a href="{{url_for('main.sheduled_toptrending', id=tweet.id)}}" class="btn btn-sm btn-blue"><i class="glyphicon glyphicon-pencil"></i></a>
                </td>
      </tr>
      {% endfor %}
      </tbody>
      </table>
      </div>
    </div>


    </div>
  </div>
{% endblock content%}

app/templates/main/twitter-home.html
{% extends 'base.html' %}

{% block content%}

<!-- Page Title -->
<div class="section section-breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Twitter Dashboard</h1>
			</div>
		</div>
	</div>
</div>

<div class="section">
	<div class="container">
		<div class="col-sm-8">
		<div class="row">
			<h2>Currently Trending in Kenya <small>  </small></h2>
			<div class="table-responsive">
                            <table class="table">
                              <thead>
                                <tr>
                                  <th>Trend</th>
                                  <th>Started</th>
                                  <th>Pos</th>
                                  <th>Prev Pos</th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for trend in top_trends %}
                                  <tr>
                                  <!-- <th scope="row"><a href="{{url_for('main.trend', id=trend.id, order='latest')}}">{{trend.name}}</a></th> -->
                                  <th scope="row">{{trend.name}}</th>
                                  <td>{{ moment(trend.started).fromNow(refresh=True) }}</td>
                                  <td>{{trend.position}}</td>
                                  {% if  trend.prev_position %}
                                  	<td>{{trend.prev_position}}</td>
                                  	{% else %}
                                  	<td>-*</td>
                                  {% endif %}

                                </tr>
                                {% endfor %}


                              </tbody>
                            </table>
                            <p>*Just started trending, has no previous position</p>
                          </div>
             </div>
             <div class="row">
             	<h2>Recently Trending in Kenya <small>  </small></h2>
			<div class="table-responsive">
                            <table class="table">
                              <thead>
                                <tr>
                                  <th>Trend</th>
                                  <th>Started</th>
                                  <th>Ended</th>
                                  <th>Tweets</th>
                                  <th>Retweets</th>
                                  <th>Users</th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for trend in recently_trending %}
                                  <tr>
                                  <th scope="row"><a href="{{url_for('main.trend_details', id=trend.id)}}">{{trend.name}}</a></th>
                                  <td>{{ moment(trend.started).fromNow(refresh=True) }}</td>
                                  <td>{{ moment(trend.ended).fromNow(refresh=True) }}</td>
                                  <td>{{trend.total_tweets}}</td>
                                  <td>{{trend.total_retweets}}</td>
                                  <td>{{trend.total_users}}</td>

                                </tr>
                                {% endfor %}


                              </tbody>
                            </table>
                          </div>
             </div>
		</div>
		<div class="col-sm-4">
			<h2>Top Profiles on Twitter <small>  </small></h2>
			{% for user in top_users %}

			<div class="twPc-div">
			    	<a class="twPc-bg twPc-block"></a>
				<div>
					<div class="twPc-button">
			            <!-- Twitter Button | you can get from: https://about.twitter.com/tr/resources/buttons#follow -->
			            <a href="https://twitter.com/{{user.screen_name}}" target="_blank" class="twitter-follow-button" data-show-count="false" data-size="large" data-show-screen-name="false" data-dnt="true">Follow @{{user.screen_name}}</a>
			            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
			            <!-- Twitter Button -->
					</div>

					<a title="{{user.name}}" href="https://twitter.com/{{user.screen_name}}" class="twPc-avatarLink" target="_blank">
						<img alt="{{user.name}}" src="{{user.profile_img_url}}" class="twPc-avatarImg" width="73" height="73">
					</a>

					<div class="twPc-divUser">
						<div class="twPc-divName" target="_blank">
							<a href="https://twitter.com/{{user.screen_name}}">{{user.name}}</a>
						</div>
						<span>
							<a href="https://twitter.com/{{user.screen_name}}" target="_blank">@<span>{{user.screen_name}}</span></a>
						</span>
					</div>

					<div class="twPc-divStats">
						<ul class="twPc-Arrange">
							<li class="twPc-ArrangeSizeFit">
								<a href="https://twitter.com/{{user.screen_name}}" title="{{user.status_count}} Tweet" target="_blank">
									<span class="twPc-StatLabel twPc-block">Tweets</span>
									<span class="twPc-StatValue">{{user.status_count}}</span>
								</a>
							</li>
							<li class="twPc-ArrangeSizeFit">
								<a href="https://twitter.com/{{user.screen_name}}/following" title="{{user.friends_count}} Following" target="_blank">
									<span class="twPc-StatLabel twPc-block">Following</span>
									<span class="twPc-StatValue">{{user.friends_count}}</span>
								</a>
							</li>
							<li class="twPc-ArrangeSizeFit">
								<a href="https://twitter.com/{{user.screen_name}}/followers" title="{{user.followers_count}} Followers" target="_blank">
									<span class="twPc-StatLabel twPc-block">Followers</span>
									<span class="twPc-StatValue">{{user.followers_count}}</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>




			{% endfor %}


			</div>
		</div>
	</div>
</div>

{% endblock content%}